[package]
name = "starshard"
version = "0.0.0-a.0"
edition = "2024"

[dependencies]
async-fs = "2.2.0"
async-io = "2.6.0"
async-lock = "3.4.2"
async-net = "2.0.0"
async-tungstenite = "0.35.0"
chacha20poly1305 = { version = "0.10.1", features = ["std"] }
clap = { version = "4.6.6", features = ["derive", "env"] }
dialoguer = "0.12.0"
dotenvy = "0.15.7"
futures-util = "0.3.34"
object-rainbow = { git = "https://github.com/parrrate/object-rainbow" }
object-rainbow-bridge = { git = "https://github.com/parrrate/object-rainbow" }
object-rainbow-cdc = { git = "https://github.com/parrrate/object-rainbow", features = [
    "fs",
    "walkdir",
] }
object-rainbow-encrypted = { git = "https://github.com/parrrate/object-rainbow" }
object-rainbow-point = { git = "https://github.com/parrrate/object-rainbow" }
sha2 = "0.11.0"
